# coding: utf-8
plt.gca().set_yscale("log")
plt.plot(bins[0:50], log10(psm),'ro')
plt.fill_between(bins[0:50],0,log10(psm))
plt.plot(bins[0:50], log10(psm),'ro')
plt.gca().set_xscale("log")
plt.plot(bins[0:50], log10(psm))
plt.scatter(bins[0:50], log10(psm))
plt.plot(bins[0:50], log10(psm))
plt.plot(bins[0:50], log10(psm),'ro')
plt.gca().set_xscale("log")
plt.gca().set_yscale("log")
plt.fill_between(bins[0:50],0,psm)
plt.title("Pristine mass in Z bins, z=10.4")
plt.ylabel("$mass_{sun}$")
plt.xlabel("Z")
